name: release build

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    permissions:
      contents: "write"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -v m -c Release -p:DebugType=None
    - name: Make release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/bin/LiveSplit.RustAlarm/release/LiveSplit.RustAlarm.dll
        generate_release_notes: false
